<a href="https://colab.research.google.com/github/hasansheikh3/MachineLearning/blob/main/Introduction_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Introduction to Pytorch by Hasan Shaikh**

In [6]:
#Creating a Tensor
# A tensor is like a ndarray in numpy
import torch
b = torch.tensor([[1,2,3],[4,5,6]])
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [2]:
#like Numpy we can create random matrices by using torch.rand function
torch.rand(2,2)

tensor([[0.8902, 0.7076],
        [0.5723, 0.6574]])

In [3]:
a = torch.rand(3,3)

In [7]:
#We can check number of rows and columns by torch.shape function
a.shape

torch.Size([3, 3])

In [8]:
#We can multiply two matrices via dot product which is represented by matmul function
matrix_a = torch.rand(2,2)
matrix_b = torch.rand(2,2)
torch.matmul(matrix_a,matrix_b)

tensor([[0.1870, 0.2270],
        [0.3659, 0.5188]])

In [9]:
matrix_a * matrix_b

tensor([[0.0106, 0.2422],
        [0.2464, 0.1804]])

In [ ]:
#Like in Numpy, we can create matrices of zeros, ones and identity
